### ISSUE TITLE
ArgumentException on Line 68 of Program.cs

### ISSUE THREAD

**Issue by dstampher** [BobLd/YOLOv4MLNet#7]
Cloned this repo, downloaded the yolov4.onnx model, changed the modelPath field to the location of the onnx file, ran the project and encountered an ArgumentException on Line 68 of Program.cs when processing kite_416.jpg.  If I remove that file name from Line 63, execution works just fine.  Strange.

@BobLd 

Here is the Stack Trace:

   at System.Drawing.Image.get_Height()
   at Microsoft.ML.Transforms.Image.ImageResizingTransformer.Mapper.<>c__DisplayClass3_0.<MakeGetter>b__1(Bitmap& dst)
   at Microsoft.ML.Transforms.Image.ImagePixelExtractingTransformer.Mapper.<>c__DisplayClass5_0`1.<GetGetterCore>b__1(VBuffer`1& dst)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.NamedOnnxValueGetterVec`1.GetNamedOnnxValue()
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.UpdateCacheIfNeeded(Int64 position, INamedOnnxValueGetter[] srcNamedOnnxValueGetters, String[] activeOutputColNames, OnnxRuntimeOutputCacher outputCache)
   at Microsoft.ML.Transforms.Onnx.OnnxTransformer.Mapper.<>c__DisplayClass12_0`1.<MakeTensorGetter>b__0(VBuffer`1& dst)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.<>c__DisplayClass8_0`1.<CreateDirectVBufferSetter>b__0(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.TypedRowBase.FillValues(TRow row)
   at Microsoft.ML.Data.TypedCursorable`1.RowImplementation.FillValues(TRow row)
   at Microsoft.ML.PredictionEngineBase`2.FillValues(TDst prediction)
   at Microsoft.ML.PredictionEngine`2.Predict(TSrc example, TDst& prediction)
   at Microsoft.ML.PredictionEngineBase`2.Predict(TSrc example)
   at YOLOv4MLNet.Program.Main() in C:\Users\david\Projects\YOLOv4MLNet-master\YOLOv4MLNet\Program.cs:line 68

**Comment by dstampher** [comment]
This seems to only be occurring on the iteration of the foreach loop (Line 63) for kite_416.jpg, when I remove that from being processed, execution works fine.  Strange.

**Comment by BobLd** [comment]
Hi @dstampher, thanks for your message. This is indeed a known issue and I have created https://github.com/dotnet/machinelearning/issues/5469 to report it. I used this repos to demonstrate the error, and unfortunately it seems the bug is still therr
